name: NewRelease

on:
  workflow_dispatch: # 修改为手动触发

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          ref: e9449feee315bf4bad4280e2c0f8fcf9755c79d4
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd extension && npm install && npm run build
      - run: sudo apt-get install -y zip && zip -r /tmp/extension-dist.zip extension/dist/
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ github.ref_name }} /tmp/extension-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
